services:
  - type: web
    name: talentscout-hiring-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python health_check.py
    startCommand: python start.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."